name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -DPLATFORM_NAME="linux"
      - run: cmake --build build
      - run: |
          mkdir -p dist
          cp build/binary2-demo dist/
          tar -czf dist/bin2.tar.gz -C dist binary2-demo
      - uses: actions/upload-artifact@v4
        with:
          name: bin2
          path: dist/bin2.tar.gz
